### ISSUE TITLE
Question - not bug in enumitem

### ISSUE THREAD

**Issue by daleif** [jbezos/enumitem#10]
I found the following code in a class file (journal class), I was just wondering, has this ever worked?

\usepackage{enumitem}
\setlist[itemize]{
  leftmargin=*,
  label=\arabic*,
  label=\roman*,
  labelsep=0.25em,
  itemsep=0pt,
  topsep=0.5\baselineskip
}

This gives me an error about \c@* I'm going to report it to the journal, but was just wondering whether this has ever worked?

In the actual code they first define a new list based on itemize, then then they apply this code to it. The class file apparently only lives on overleaf, which might be why it has not been fixed (AFAIK overleaf uses an older TeXLive).

**Comment by jbezos** [comment]
To be honest, I have no idea, but I'd say something like that never worked.
