### ISSUE TITLE
enumitem 3.7 no longer fully calc enabled

### ISSUE THREAD

**Issue by FrankMittelbach** [jbezos/enumitem#14]
version 3.7 contains the line 
```
\let\enit@setlength\setlength
```
As a result if the calc package is loaded later \enit@setlength will keep the non-calc definition. It should therefore be defined as
```
\def\enit@setlength{\setlength}
```
to remove the unnecessary dependency on package loading order

**Comment by jbezos** [comment]
A mistake, indeed. I'll fix it.
