### ISSUE TITLE
Documentation request

### ISSUE THREAD

**Issue by daleif** [jbezos/enumitem#15]
It seems users are a bit baffled about which lengths are used when in regards to lists. 

Example: https://tex.stackexchange.com/q/473886/3929

Zarko suggested adding an image similar to page 137 in the memoir manual to the enumitem documentation might help users understand the relations ships.

It might also be an idea to visually explain the consequences of say leftmargin=* etc.

**Comment by jbezos** [comment]
And not only users, you know. With \DrawEnumitemLabel I discovered
I was misunderstanding some things, and I've had some surprises.
Now I realize this is the very first macro I should have written :-).
I recommend `layouts` in the manual, but yes, you are right.
