### ISSUE TITLE
Cannot install using `tlmgr`

### ISSUE THREAD

**Issue by undergroundwires** [jbezos/enumitem#22]
http://mirror.utexas.edu/ctan/systems/texlive/tlnet/archive/enumitem.tar.xz appears to be dead.

# Command

`tlmgr install enumitem`

# Output

```txt
Unable to download the checksum of the remote TeX Live database,
but found a local copy, so using that.

You may want to try specifying an explicit or different CTAN mirror,
or maybe you need to specify proxy information if you're behind a firewall;
see the information and examples for the -repository option at
https://tug.org/texlive/doc/install-tl.html
(and in the output of install-tl --help).

tlmgr: package repository http://mirror.utexas.edu/ctan/systems/texlive/tlnet (not verified: unknown)
[1/1, ??:??/??:??] install: enumitem [14k]
TLPDB::_install_data: downloading did not succeed (download_file failed) for http://mirror.utexas.edu/ctan/systems/texlive/tlnet/archive/enumitem.tar.xz
tlmgr: package log updated: /opt/texlive/texdir/texmf-var/web2c/tlmgr.log
```

**Comment by FrankMittelbach** [comment]
Sorry can't help you here. This is a distribution/setup problem and we don't distribute packages. This is done by the people managing the CTAN network. Mirrors go out of service sometimes and as the  output suggests you may have to redirect/change the source for tlmgr.

**Comment by muzimuzhi** [comment]
Also note that the http://mirror.utexas.edu/ says

> ******************************************************************************
>   NOTICE: The ftp.utexas.edu service will be discontinued as of August 5,
>           2020. All mirrored content will be removed from this server as of
>           that date, and the server itself will be shut down on November 5,
>           2020.
> *****************************************************************************

You can use `tlmgr option repository [ctan|<ctan mirror>/systems/texlive/tlnet]` to set the CTAN mirror used by tlmgr, see https://www.tug.org/texlive/doc/tlmgr.html#option.

**Comment by undergroundwires** [comment]
Thank you for your super fast response & help @FrankMittelbach @muzimuzhi . Awesome! 🍻

I got it working with `tlmgr --repository http://mirror.ctan.org/systems/texlive/tlnet install enumitem` and it works smoothly.

Closing this issue.
