### ISSUE TITLE
before/after/first confusion

### ISSUE THREAD

**Issue by kalekje** [jbezos/enumitem#30]
Can it be confirmed/clarified that the following is true when using the before, after, and first keys? Additionally, may I suggest the addition of a last or final key to inject something before itemize/enumerate is ended? See below:
```
<before>
\begin{itemize}
<first>
\item
<last>  --- Feature request
\end{itemize}
<after>
```

**Comment by muzimuzhi** [comment]
- As documented, `<before>` is used in the second mandatory argument of `\list`, hence already after`\begin{itemize}`.
 - Similarly, `<after>` is used at the place where the requested "last of final key" would be used. You can test this with `first={\item first}, after={\item after}`.

Combine all these, input
```tex
\begin{itemize}
  <env content>
\end{itemize}
```
is more or less equivalent to
```tex
<some settings>
\list{<labeling>}{<spacing settings> <before>}
  <first>
  <env content>
  <after>
\endlist
<some settings>
```
You can find some intro to `\list` here: https://latexref.xyz/list.html.
