### ISSUE TITLE
what is the command of `newlist`'s label ?

### ISSUE THREAD

**Issue by syvshc** [jbezos/enumitem#32]
Here I know evironment `enumerate`'s label command is `\labelenumi`, \labelenumii`, ...

![image](https://user-images.githubusercontent.com/38098591/145970730-d605678c-d94d-43c7-8d65-435ac79dae81.png)

But if I new a list like `\newlist{exercise}{enumerate}{2}`, what is evironment `exercise`'s label command?

**Comment by jbezos** [comment]
See section 7 of the manual.

**Comment by syvshc** [comment]
> See section 7 of the manual.

I found that, And I met another problem, I added it in my issue.

**Comment by muzimuzhi** [comment]
new problem, new issue
