### ISSUE TITLE
Feature request: braces spanning items

### ISSUE THREAD

**Issue by jessexknight** [jbezos/enumitem#35]
Thanks for all your LaTeX contributions.

I recently came across [this solution](https://tex.stackexchange.com/questions/433933) to drawing vertical braces around multiple list items. I thought:  _this should be part of a package..._ and enumitem would be natural maybe. Would you consider adding this feature? I understand if not within the scope.

If so, some details we could consider:

- left & right-side braces supported
- right-side spacing automatically computed
- where _should_ the command be invoked & how to indicate items spanned e.g. `{<from>}{<to>}`
- any offset for multiple overlapping braces?
- any support for horizontal lists?

If I get time, I will try to generalize the solution in the original post to these specs...

Thanks for considering

**Comment by jbezos** [comment]
Sorry, but this feature is more related to tables, diagrams, etc. I don’t think `enumitem` is the proper place.
