### ISSUE TITLE
Enumerate item with circled label has inconsistent font size

### ISSUE THREAD

**Issue by zwz** [jbezos/enumitem#41]
I want to have enumerate item with circled label.
I tried `circledtext` package, which provides better results than `\textcircled`. 
Here is mwe
```
\documentclass{article}
\usepackage{enumitem}
\usepackage{circledtext}
\newlist{steps}{enumerate}{2}
\setlist[steps,1]{label=(\arabic*)}
\setlist[steps,2]{label=\circledtext{\arabic*}}

\begin{document}
\begin{steps}
\item
  item1
  \begin{steps}
  \item
    item1.1
  \item
    item1.2
  \end{steps}
\item
  item2
\end{steps}
\end{document}
```
You will see that the circled label before `item1.1` is obviously bigger than that before `item1`.
I tried `\setlist[steps,2]{label=\circledtext{\tiny\arabic*}}` and `\setlist[steps,2]{font=\tiny, label=\circledtext{\arabic*}}`, 
but had no effect.

**Comment by muzimuzhi** [comment]
> You will see that the circled label before `item1.1` is obviously bigger than that before `item1`.

What's the output you got? I can only get smaller label before `item1.1` than that before `item1`.

pdflatex:
![image](https://user-images.githubusercontent.com/6376638/211414197-2ec47470-c9d1-4a88-9d18-102bedec07d9.png)

xelatex:
![image](https://user-images.githubusercontent.com/6376638/211414573-d1f46d19-1058-4239-bf15-d9371db9eaee.png)

**Comment by zwz** [comment]
@muzimuzhi Yes, you are right.
In fact, I was using `\documentclass{ctexart}` with xelatex before I posted the issue.

Anyway, how could I make the label the same size as the text?

**Comment by jbezos** [comment]
Please, keep in mind the issue tracker is not intended as a general support forum, but for reporting bugs and feature requests. For other type of questions, consider asking at https://tex.stackexchange.com/ . I'm closing this issue because it’s neither a bug nor a feature request.

**Comment by zwz** [comment]
@jbezos Well, I am not sure, but it seems a bug to me.
I will try https://tex.stackexchange.com/.
