### ISSUE TITLE
texnia.com don't work as expected.

### ISSUE THREAD

**Issue by quark67** [jbezos/enumitem#44]
On bottom of the first page of the PDF documentation of the enumitem package, there is a link to http://www.texnia.com/enumitem.html, but this page is redirected to http://www.texnia.com/cgi-sys/defaultwebpage.cgi which display a "SORRY!" message about server problem or IP address problem. The same address (http://www.texnia.com/enumitem.html) appears also on the CTAN page of the package.

**Comment by jbezos** [comment]
It’s up again (but the contact page still fails).
