### ISSUE TITLE
Any difference between the keys `font` and `format`?

### ISSUE THREAD

**Issue by SwitWu** [jbezos/enumitem#45]
Do the two keys `font` and `format` have any difference? According to the manual, `format` is a synonym for `font`.

**Comment by muzimuzhi** [comment]
From the source code, `font` is just a/an (semantic) alias for `format`.
https://github.com/jbezos/enumitem/blob/1bdcad0987823b3716c86b126b3863f895ea9c4a/enumitem.sty#L434-L441

**Comment by jbezos** [comment]
Just use the name that best fits what you're setting. That’s all.
