### ISSUE TITLE
Nested list modified by parents

### ISSUE THREAD

**Issue by tobiasBora** [jbezos/enumitem#47]
If I have a nested list (enumitem-based) like:
```
\begin{itemize}
\item A
\item A
\item
  \begin{enumerate}[nosep,leftmargin=3cm,labelsep=0pt]
  \item B
  \item K
    \begin{itemize}
    \item Z
    \item P
    \end{itemize}
  \end{enumerate}
\end{itemize}
```
the nested list will take the value of the parent, giving weird results like:

[![enter image description here][1]][1]

(see how Z/P are close to the label)

Is it possible to "isolate" the setting to a single list? I guess I could manually write all parameters, in the definition of `itemize`, but I don't know what are the default values, nor what is the list of all values to set (and it seems a bit dirty).

MWE

```
\documentclass{article}
\usepackage{xcolor}
\usepackage{enumitem}
\newcommand*{\marvosymbol}[1]{{\fontfamily{mvs}\fontencoding{U}\fontseries{m}\fontshape{n}\selectfont\char#1}}
\setlist[itemize]{label={\strut\textcolor{blue!50!white}{\marvosymbol{123}}},leftmargin=6mm,}


\begin{document}


\begin{itemize}
\item A
\item A
\item
  \begin{enumerate}[nosep,leftmargin=3cm,labelsep=0pt]
  \item B
  \item K
    \begin{itemize}
    \item Z
    \item P
    \end{itemize}
  \end{enumerate}
\end{itemize}

\end{document}
```

  [1]: https://i.stack.imgur.com/tvJ3c.png

**Comment by muzimuzhi** [comment]
`\labelsep` is initially .5em in standard document classes.

Example below uses
```tex
\expanded{\noexpand\setlist[itemize]{labelsep=\the\labelsep}}
```
to give `labelsep` a default value.

Note this is different from setting `labelsep=.5em`, since em is a relative unit, but here we just need the exact length of .5em at the time of loading document class.

<details><summary>Full example</summary>
<p>

```tex
\documentclass{article}
\usepackage{enumitem}

\setlist{nosep} % for tighter output
\setlist[itemize]{label={\texttt{+}}}
% pass curent value of \labelsep to "labelsep" key
\expanded{\noexpand\setlist[itemize]{labelsep=\the\labelsep}}

\begin{document}
\begin{itemize}
\item A
\item A
  \begin{enumerate}
  \item default \texttt{labelsep}
  \item K
    \begin{itemize}
    \item Z
    \item P
    \end{itemize}
  \end{enumerate}
\item A
  \begin{enumerate}[labelsep=0pt]
  \item local, zero \texttt{labelsep}
  \item K
    \begin{itemize}
    \item Z
    \item P
    \end{itemize}
  \end{enumerate}
\end{itemize}

\end{document}
```

</p>
</details>

![image](https://github.com/jbezos/enumitem/assets/6376638/f9c40c98-02f2-4f4a-989e-eac33331bd76)

**Comment by tobiasBora** [comment]
Thanks a lot. But I guess there are many other properties one might want to preserve no? (like `nosep` would certainly modify other lengths) Is there a way to reset them all to their default value?

**Comment by tobiasBora** [comment]
Thanks a lot! Would be great to have a key to enable this reset!

**Comment by muzimuzhi** [comment]
You could try it yourself first.

**Comment by jbezos** [comment]
The behavior of `labelsep` is explained in the manual. I have no plans to add new features in this regard, sorry.
