### ISSUE TITLE
Interaction with `\listI` and top-level parameters

### ISSUE THREAD

**Issue by sim642** [jbezos/enumitem#50]
I am porting an old document class, which uses low level customization of lists by redefining `\@listi`, etc, to use `enumitem` instead. However, I've had hard time getting the output to be identical.

Namely, what I eventually realized is that `enumitem` doesn't seem to do anything about `\@listI`, which is called by standard `\normalsize`. So, unless I keep its old low-level definition, or do the following
```latex
\def\@listI{
  \enit@setkeys{list}%
  \enit@setkeys{listi}%
}
```
Some use of `\normalsize` is calling the standard definition with standard list parameters, instead of those I've set using `\setlist`. Also, `\setlist[trivlist]` doesn't seem to help entirely.

Moreover, some packages like `biblatex` seem to assume top-level list parameter definitions like `\itemsep`. Standard classes seem to do that by expanding `\@listi` immediately after defining it.
However, `enumitem` doesn't seem to have any way to change those? Again, `\setlist[trivlist]` doesn't seem to be enough for everything to come out identical.

It seems that `enumitem` only wants to redefine standard list types like `itemize` but not actually change the standard `\@listi`, etc. Am I correct that `enumitem` cannot thus completely replace the low level redefinitions? If so, why is that?

**Comment by jbezos** [comment]
Please, explain what you want to achieve, with an example.

**Comment by sim642** [comment]
I want the `enumitem` equivalent of this:
```latex
\def\@listi{\leftmargin\leftmargini
              \labelwidth\leftmarginii
    \topsep   2\p@   \@plus  0.5\p@ \@minus0.5\p@
    \partopsep0.5\p@   \@plus0.5\p@   \@minus0.5\p@
    \parsep   1\p@   \@plus0.5\p@
    \itemsep  1\p@ \@plus0.5\p@ \@minus0.5\p@}
\let\@listI\@listi
\@listi
```

I tried this (which requires annoying duplication), but it's not equivalent:
```latex
\setlist[1]{
  leftmargin= \leftmargini,
  labelwidth=\leftmarginii,
  topsep=   2\p@   \@plus  0.5\p@ \@minus0.5\p@,
  partopsep= 0.5\p@   \@plus0.5\p@   \@minus0.5\p@,
  parsep=   1\p@   \@plus0.5\p@,
  itemsep=  1\p@ \@plus0.5\p@ \@minus0.5\p@
}
% also override trivlist for flushright, etc
\setlist[trivlist]{
  leftmargin= \leftmargini,
  labelwidth=\leftmarginii,
  topsep=   2\p@   \@plus  0.5\p@ \@minus0.5\p@,
  partopsep= 0.5\p@   \@plus0.5\p@   \@minus0.5\p@,
  parsep=   1\p@   \@plus0.5\p@,
  itemsep=  1\p@ \@plus0.5\p@ \@minus0.5\p@
}
```

**Comment by jbezos** [comment]
Thanks, but I’m interested in the ‘what’ (and the ‘why’), not in the ‘how’.

**Comment by jbezos** [comment]
I’m closing this issue because no further clarification was provided.
